### PR TITLE
update c/cpp grammars

### PR DESCRIPTION
**Pull request by alexl0gan**
#### What it does
Update cpp package to use vscode grammar files as defined here:
https://github.com/jeff-hykin/cpp-textmate-grammar
https://github.com/microsoft/vscode/tree/master/extensions/cpp/syntaxes

### CODE REVIEW

**Comment by thegecko** [comment]
Please reference the same PR against eclipse-theia

**Comment by alexl0gan** [comment]
@thegecko we won't be able to upstream this pr because in theia master they have removed the cpp package and moved all language definitions to the textmate-grammars package.

**Comment by thegecko** [comment]
In which case do we need to implement changes on that package instead?

**Comment by alexl0gan** [comment]
@thegecko I can make a pr in theia for textmate-grammars, and pr in our fork for cpp, then when we upgrade we will get the change.

**Comment by alexl0gan** [comment]
Corresponding PR in theia https://github.com/eclipse-theia/theia/pull/6944

**Comment by alexl0gan** [comment]
@arekzaluski can I merge this? 

Not sure how to proceed on the Theia side. They are going to deprecate the textmate-grammars package  so they wouldn't take my pr.

Vince had this suggestion https://github.com/eclipse-theia/theia/pull/6944#issuecomment-577220762

**Comment by thegecko** [comment]
Basically we need to ensure this patch is no longer needed when we upgrade theia.

**Comment by thegecko** [comment]
Looks like we need to switch to using that extension when we upgrade to theia 0.15.

**Comment by alexl0gan** [comment]
Creating new pr for theia 12

**Pull request closed without merging**
